# docker-compose.override.yml
name: bambaiba_dev

services:
  bambaiba_api:
    build:
      context: .
      dockerfile: src/BambaIba.Api/Dockerfile
      target: dev
    image: bambaiba_api
    container_name: bambaiba_api
    command: ["dotnet", "watch", "run", "--project", "src/BambaIba.Api/BambaIba.Api.csproj"]
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: true
      ASPNETCORE_URLS: "http://+:7000;https://+:7001"
      ConnectionStrings__DefaultConnection: "Host=bambaiba_db;Port=5432;Database=bambaiba_db;Username=admin;Password=admin123;"
    volumes:
      - .:/app:cached
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    ports:
      - "7000:7000"
      - "7001:7001"
    depends_on:
      - bambaiba_db
      - redis
      - minio
    restart: unless-stopped
    networks:
      - bambaiba_network
